version: "3.7"

services:

    nginx:
        image: nginx:${NGINX_VERSION}
        ports:
            - ${NGINX_PORT}:80
        depends_on:
            - php
        environment:
            - NGINX_PORT=${NGINX_PORT}
            - NGINX_SERVER_ROOT=${PATH_DESTINATION}
        volumes:
            - ./:/var/www/html/
            - ./.docker/nginx/:/etc/nginx/templates/

    php:
        image: php:${PHP_VERSION}-fpm
        build:
            context: .docker/php/
            dockerfile: Dockerfile
            args:
                - PHP_VERSION=${PHP_VERSION}
        links:
            - mysql
        volumes:
            - ./:/var/www/html/
            - ./.docker/php/:/usr/local/etc/php/

    mysql:
        image: mysql:${MYSQL_VERSION}
        command: --default-authentication-plugin=mysql_native_password # fix mysql 8 authentification issue
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
        volumes:
            - ./.docker/mysql/databases:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
        restart: always
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - PMA_HOST=mysql

    node:
        image: node:${NODE_VERSION}
        build:
            context: .docker/node/
            dockerfile: Dockerfile
            args:
                - NODE_VERSION=${NODE_VERSION}
        ports:
            - 3000:3000 # browser-sync server
            - 3001:3001 # browser-sync ui
        working_dir: /usr/src/app
        volumes:
            - ./:/usr/src/app/
        command: sh -c "npm start"